/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { ChatCompletionMessageToolCallChunk } from './ChatCompletionMessageToolCallChunk';
/**
 * A chat completion delta generated by streamed model responses.
 */
export type ChatCompletionStreamResponseDelta = {
    /**
     * The contents of the chunk message.
     */
    content?: string | null;
    /**
     * Deprecated and replaced by `tool_calls`. The name and arguments of a function that should be called, as generated by the model.
     * @deprecated
     */
    function_call?: {
        /**
         * The arguments to call the function with, as generated by the model in JSON format. Note that the model does not always generate valid JSON, and may hallucinate parameters not defined by your function schema. Validate the arguments in your code before calling your function.
         */
        arguments?: string;
        /**
         * The name of the function to call.
         */
        name?: string;
    };
    tool_calls?: Array<ChatCompletionMessageToolCallChunk>;
    /**
     * The role of the author of this message.
     */
    role?: ChatCompletionStreamResponseDelta.role;
};
export namespace ChatCompletionStreamResponseDelta {
    /**
     * The role of the author of this message.
     */
    export enum role {
        SYSTEM = 'system',
        USER = 'user',
        ASSISTANT = 'assistant',
        TOOL = 'tool',
    }
}

