/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { ChatCompletionMessageToolCall } from './ChatCompletionMessageToolCall';
/**
 * The tool calls generated by the model, such as function calls.
 */
export type ChatCompletionMessageToolCalls = Array<ChatCompletionMessageToolCall>;
