/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { ChatCompletionMessageToolCalls } from './ChatCompletionMessageToolCalls';
/**
 * A chat completion message generated by the model.
 */
export type ChatCompletionResponseMessage = {
    /**
     * The contents of the message.
     */
    content: string | null;
    tool_calls?: ChatCompletionMessageToolCalls;
    /**
     * The role of the author of this message.
     */
    role: ChatCompletionResponseMessage.role;
    /**
     * Deprecated and replaced by `tool_calls`. The name and arguments of a function that should be called, as generated by the model.
     * @deprecated
     */
    function_call?: {
        /**
         * The arguments to call the function with, as generated by the model in JSON format. Note that the model does not always generate valid JSON, and may hallucinate parameters not defined by your function schema. Validate the arguments in your code before calling your function.
         */
        arguments: string;
        /**
         * The name of the function to call.
         */
        name: string;
    };
};
export namespace ChatCompletionResponseMessage {
    /**
     * The role of the author of this message.
     */
    export enum role {
        ASSISTANT = 'assistant',
    }
}

