/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
/**
 * Represents the url or the content of an image generated by the OpenAI API.
 */
export type Image = {
    /**
     * The base64-encoded JSON of the generated image, if `response_format` is `b64_json`.
     */
    b64_json?: string;
    /**
     * The URL of the generated image, if `response_format` is `url` (default).
     */
    url?: string;
    /**
     * The prompt that was used to generate the image, if there was any revision to the prompt.
     */
    revised_prompt?: string;
};

